name: Upload Files

on:
  push:
    branches:
      - Latest-Release

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'latest'
        destination_repo: 'helpboard-app/V3-UI-Server'
        destination_branch: 'main'
        destination_folder: 'static'
        user_email: 'brendenstahle@gmail.com'
        user_name: 'Brenden2008'
        commit_msg: '[GHA] Copied the latest version of Helpboard UI.'
